 var countryApp = angular.module('countryApp', []);
      countryApp.controller('CountryCtrl', function ($scope){
        $scope.countries = [
          {"name": "Ideals", "paragraphs": "As an individual, I will promote integrity, character, honesty, self-confidence, and uphold my financial responsibilities. As a Sorority, we will promote unity, friendship, professionalism, follow traditions, and maintain our image. As an integral part of the school, we will promote engineering and technical science activities, high scholastic standards, and strong relations between students and faculty. As an active member in the community, we will promote understanding, knowledge, and communication within our profession.", image: "img1.JPG"},
          {"name": "Objectives", "paragraphs": "To create friendships while promoting self-confidence, professionalism and motivation among female engineers and technical scientists of all curricula. To work for the betterment of the individual and the Sorority as a whole. To create a friendly and warm environment among its members. To promote the welfare and interest of the profession. To strengthen the relationships between students and faculty. To enhance educational achievements and scholarship. To help develop the highest standards of personal integrity and character. To foster and maintain the bond of sisterhood through a continuing program for the alumnae."},
          {"name": "Other information","paragraphs": "Alpha Omega Epsilon is a professional and social sorority composed of female engineering and technical science students and alumnae. Founded on November 13, 1983, the sorority promotes ideals and objectives that further the advancement of female engineers and technical scientists and builds a foundation for lifelong bonds of sisterhood. Alpha Omega Epsilon prohibits discrimination against and harassement of any member or potential new member because of race, color, national or ethnic origin, age, religion, disability, sexual orientation, gender identity and expression, veteran status or any other characteristic protected under federal or applicable state law."}
        ];
        
      });
